spring:
  config.activate.on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}        # jdbc:postgresql://<dev-internal-host>:5432/<db>?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update           # convenient for dev